/**
 * Correlation IDs (SSRK-183)
 * Defines stream_id and trace_id rules for cross-service correlation
 */

/**
 * Correlation ID Rules (SSRK-183)
 *
 * stream_id:
 * - Generated by server per connection
 * - Format: "stream-{timestamp}-{random}"
 * - Stable for the lifetime of a single SSE connection
 * - Included in all server logs and events
 * - Passed to client in control.open event
 * - Client stores and includes in its logs
 *
 * trace_id:
 * - Optional, provided by consumer (client)
 * - Passed via X-Trace-ID header or ?trace_id query param
 * - Server captures and includes in logs and events
 * - Enables cross-service distributed tracing
 * - If not provided, not included (no default generation)
 */

/**
 * Generate a stream ID (SSRK-184)
 * Called by server for each new connection
 *
 * @returns {string} Unique stream identifier
 */
export function generateStreamId() {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).slice(2, 10);
  return `stream-${timestamp}-${random}`;
}

/**
 * Validate stream ID format
 *
 * @param {string} streamId - Stream ID to validate
 * @returns {boolean} True if valid
 */
export function isValidStreamId(streamId) {
  if (!streamId || typeof streamId !== 'string') {
    return false;
  }
  // Must start with 'stream-' and have timestamp-random format
  return /^stream-[a-z0-9]+-[a-z0-9]+$/.test(streamId);
}

/**
 * Validate trace ID format
 * Accepts common trace ID formats (W3C, Jaeger, Zipkin, custom)
 *
 * @param {string} traceId - Trace ID to validate
 * @returns {boolean} True if valid
 */
export function isValidTraceId(traceId) {
  if (!traceId || typeof traceId !== 'string') {
    return false;
  }
  // Accept alphanumeric with dashes, 1-128 chars
  // Covers W3C trace-id (32 hex), Jaeger (32 hex), custom formats
  return /^[a-zA-Z0-9-]{1,128}$/.test(traceId);
}

/**
 * Extract trace ID from request headers or query params (SSRK-187)
 *
 * @param {Object} request - HTTP request object
 * @returns {string|null} Trace ID if found and valid
 */
export function extractTraceId(request) {
  // Check header first (preferred)
  const headerTraceId =
    request.headers?.['x-trace-id'] ||
    request.headers?.['x-request-id'] ||
    request.headers?.['traceparent']?.split('-')[1]; // W3C format

  if (headerTraceId && isValidTraceId(headerTraceId)) {
    return headerTraceId;
  }

  // Check query param as fallback
  const queryTraceId = request.query?.trace_id;

  if (queryTraceId && isValidTraceId(queryTraceId)) {
    return queryTraceId;
  }

  return null;
}

/**
 * Correlation context object
 * Holds both stream_id and trace_id for a connection
 */
export class CorrelationContext {
  /**
   * Create correlation context
   * @param {Object} options - Configuration
   */
  constructor(options = {}) {
    this.streamId = options.streamId || null;
    this.traceId = options.traceId || null;
  }

  /**
   * Set stream ID
   */
  setStreamId(streamId) {
    this.streamId = streamId;
  }

  /**
   * Set trace ID
   */
  setTraceId(traceId) {
    if (traceId && isValidTraceId(traceId)) {
      this.traceId = traceId;
    }
  }

  /**
   * Get correlation fields for logging
   * @returns {Object} Object with stream_id and optionally trace_id
   */
  toLogFields() {
    const fields = {};

    if (this.streamId) {
      fields.stream_id = this.streamId;
    }

    if (this.traceId) {
      fields.trace_id = this.traceId;
    }

    return fields;
  }

  /**
   * Get correlation fields for event envelope
   * @returns {Object} Object with stream_id and optionally trace_id
   */
  toEventFields() {
    return this.toLogFields();
  }

  /**
   * Check if context has stream ID
   */
  hasStreamId() {
    return !!this.streamId;
  }

  /**
   * Check if context has trace ID
   */
  hasTraceId() {
    return !!this.traceId;
  }
}

/**
 * Create a correlation context
 */
export function createCorrelationContext(options) {
  return new CorrelationContext(options);
}

export default {
  generateStreamId,
  isValidStreamId,
  isValidTraceId,
  extractTraceId,
  CorrelationContext,
  createCorrelationContext,
};
